FROM python

RUN mkdir LisaSimpson
COPY main.py ./LisaSimpsonPruebas/
COPY requeriments.txt ./LisaSimpsonPruebas/

RUN pip install -r ./LisaSimpsonPruebas/requeriments.txt


CMD ["python","LisaSimpsonPruebas/main.py"]